Fix macro redefinition error for GROONGA_NORMALIZER_MYSQL_EMBED
We got the following error when we built Groonga with
MariaDB.

```
/home/buildbot/storage/mroonga/groonga-normalizer-mysql/normalizers/../config.h:22:9: error: "GROONGA_NORMALIZER_MYSQL_EMBED" redefined [-Werror]
   22 | #define GROONGA_NORMALIZER_MYSQL_EMBED
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<command-line>: note: this is the location of the previous definition
```

So we added `#ifndef` guard around
GROONGA_NORMALIZER_MYSQL_EMBED to prevent redefinition
conflicts when the macro is also defined via
command-line flags during compilation.